# permissions for end users to edit demoresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demoresource-editor-role
rules:
- apiGroups:
  - tools.opdev.io
  resources:
  - demoresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.opdev.io
  resources:
  - demoresources/status
  verbs:
  - get
